config/routes.rb
App::Application.routes.draw do

  resources :roles

  resources :records

  resources :agendas

  resources :visitors

  resources :employees
  
  root :to => 'home#index'

  resources :companies

end

app/models/employee.rb
class Employee
  include Mongoid::Document
  field :name, type: String
  #embedded_in :company
  belongs_to :company, :inverse_of => :employees
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <!-- <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div> -->
  <div class="field ui input">
    <%= f.select :company_id, Company.all.collect { | x | [x.name, x.id]}, {}, :class => '' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1> <%= link_to 'New Employee', new_employee_path, :class => 'ui green button' %>

<table class="ui celled striped table">
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td>
      <% if employee.company? %>
        <%= employee.company.name %>
      <% end %>
    </td>
    <!-- <td><%= link_to 'Show', employee %></td> -->
    <td><%= link_to 'Edit', edit_employee_path(employee), :class => 'ui blue button' %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'ui red button' %></td>
  </tr>
<% end %>
</table>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<% if notice %>
	<div class="ui info message">
	  <p id="notice"><%= notice %></p>
	</div>
<% end %>

<h1> User "<%= @employee.name %>"</h1>
<div class="ui raised segment">
<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Company:</b>
  <%= @employee.company.name %>
</p>
</div>

<%= link_to 'Edit', edit_employee_path(@employee), :class => 'ui button primary' %>
<%= link_to 'Back', employees_path %>