config/routes.rb
App::Application.routes.draw do

  resources :roles

  resources :records

  resources :agendas

  resources :visitors

  resources :employees
  
  root :to => 'home#index'

  resources :companies

end

app/models/visitor.rb
class Visitor
  include Mongoid::Document
  field :name, type: String
  field :last_name, type: String
  #embedded_in :company
  belongs_to :company
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visitors }
    end
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visitor }
    end
  end

  # GET /visitors/new
  # GET /visitors/new.json
  def new
    @visitor = Visitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visitor }
    end
  end

  # GET /visitors/1/edit
  def edit
    @visitor = Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(params[:visitor])

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render json: @visitor, status: :created, location: @visitor }
      else
        format.html { render action: "new" }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visitors/1
  # PUT /visitors/1.json
  def update
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_for(@visitor) do |f| %>
  <% if @visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2> 
      <ul>
      <% @visitor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui header">
    <%= f.label :name %>
  </div>
  <div class="ui input">
    <%= f.text_field :name %>
  </div>
  <div class="ui header ">
    <%= f.label :last_name %>
  </div>
  <div class="ui input">
    <%= f.text_field :last_name %>
  </div>
  <div class="ui header">
    <%= f.label :company %>
    
  </div>
  <div class="field ui input">
    <%= f.select :company_id, Company.all.collect { | x | [x.name, x.id]}, {}, :class => '' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'ui button green' %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing visitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<h1>Listing visitors</h1>
<%= link_to 'New Visitor', new_visitor_path, :class => 'ui button green' %>
<table class="ui table">
  <tr>
    <th>Name</th>
    <th>Last name</th>
    <th>Company</th>
    <th>Actions</th>
    <!-- <th></th>
    <th></th> -->
  </tr>

<% @visitors.each do |visitor| %>
  <tr>
    <td><%= visitor.name %></td>
    <td><%= visitor.last_name %></td>
    
    <td>
      <% if visitor.company? %>
    <%= visitor.company.name %>

    <% end %>
    </td>
    <!-- <td><%= link_to 'Show', visitor %></td> -->
    <td><%= link_to 'Edit', edit_visitor_path(visitor), :class => 'ui button blue' %>
        <%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'ui button red' %>
    </td>
  </tr>
<% end %>
</table>

app/views/visitors/new.html.erb
<h1>New visitor</h1>

<%= render 'form' %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @visitor.name %>
</p>

<p>
  <b>Last name:</b>
  <%= @visitor.last_name %>
</p>

<p>
  <b>Company:</b>
  <%= @visitor.company.name %>
</p>


<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>