config/routes.rb
App::Application.routes.draw do

  resources :roles

  resources :records

  resources :agendas

  resources :visitors

  resources :employees
  
  root :to => 'home#index'

  resources :companies

end

app/models/company.rb
class Company
  include Mongoid::Document
  field :name, type: String
  #embeds_one :employees
  has_many :employees
  belongs_to :role
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui header">
    <%= f.label :name %>
  </div>
  <div class="field ui input">
    <%= f.text_field :name %>
  </div>

   <div class="ui header">
    <%= f.label :role %>
  </div>
  <div class="field ui input">
     <%= f.select :role_id, Role.all.collect { | x | [x.name, x.id]}, {}, :class => '' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', :class => 'ui button green' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>
<%= link_to 'New Company', new_company_path, :class => 'ui green button' %>
<table class="ui celled striped table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <!-- <td><%= link_to 'Show', company %></td> -->
    <td><%= link_to 'Edit', edit_company_path(company), :class => 'ui blue button' %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'ui red button' %></td>
  </tr>
<% end %>
</table>

app/views/companies/new.html.erb
<h1>New company</h1>
<div class="ui divider"></div>
<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>