config/routes.rb
App::Application.routes.draw do

  resources :roles

  resources :records

  resources :agendas

  resources :visitors

  resources :employees
  
  root :to => 'home#index'

  resources :companies

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registro Agil</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="../../Semantic/dist/semantic.css" />
  <script src="../../Semantic/dist/semantic.js"></script>
  <style type="text/css">
  .ui.vertical.menu {
		width: 100%;
	}
	table th {
		padding: 10px;
	}

	a:hover {
		background: inherit;
	}
   </style>
</head>
<body class="">
	<div class="push">
		<div class="ui padded grid white">
			<div class="three wide middle column">
		      <h1 class="">
		        Registro Agil
		      </h1>
		      <div class="ui vertical menu">
		      		<%= link_to 'Companies', companies_path, :class => 'item' %>
		      		<%= link_to 'Employees', employees_path, :class => 'item' %>
		      		<%= link_to 'Visitors', visitors_path, :class => 'item' %>
		      		<%= link_to 'Agenda', agendas_path, :class => 'item' %>
				  	<%= link_to 'Record', records_path, :class => 'item' %>
				  	<%= link_to 'Roles', roles_path, :class => 'item' %>
				  <!-- <a class="item">
				    <i class="child icon"></i> Employees
				  </a> -->

				  <!-- <a class="item">
				    <i class="calendar icon"></i> Agendas
				  </a> -->
				  <!-- <a class="item">
				    <i class="user icon"></i> Visitors
				  </a> -->
				  <!-- <a class="item"><i class="settings icon"></i> Account Settings</a> -->
				</div>
				<div class="column">
				    <div class="ui segment">
				      <img src="/images/avatar/steve.jpg" class="ui fluid image">
				    </div>
				</div>
		    </div>
		    <div class="ten wide right column">
		      <p>
		      	<%= yield %>
		      </p>
		    </div>
		</div>
	</div>
</body>
</html>